---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: noussydjimi/docplanner:front
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 80
