apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: docplanner
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  providerRef:
    name: docplanner
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: docplanner
spec:
  subnetSelector:
    kubernetes.io/role/internal-elb: "1"
  securityGroupSelector:
    Name: "{{ .Values.securityGroupSelector }}"
